### ISSUE TITLE
[i18n] Separate 'Custom Fonts' plugin brand name from other strings

### ISSUE THREAD

**Issue by pedro-mendonca** [brainstormforce/custom-fonts#74]
Congratulations for the awesome plugin!

While translating it, I've found that translating "Custom Fonts" strings also translates the plugin name, which is a bad practice and isn't desireable.

As this plugin brand name is exactly the same string that is used in many menu and title translatable strings, I suggest to add some context to each "Custom Fonts" string to avoid mixing it with the translation from the actual plugin name.
The plugin name shouldn't be translated for branding reasons.

Let me know if you're interested in a PR with a fix suggestion :)

**Comment by imnavanath** [comment]
Thanks for your valuable contribution @pedro-mendonca, considering this in v2.0.2 update. 👍
